### ISSUE TITLE
Django 1.7 Migrations and  django-pgfields v1.5a1

### ISSUE THREAD

**Issue by ghost** [lukesneeringer/django-pgfields#10]
``` python
class Migration(migrations.Migration):

 ...
    operations = [
        migrations.CreateModel(
            ...
            bases=(django.db.models.base.NewBase,),
```

After I removed bases - it's all ok... If not:

``` python
(byvshie) iMac-Alexander:byvshie lorddaedra$ ./manage.py makemigrations
Migrations for 'byvshiebase':
  0006_auto_20140418_0411.py:
    - Create model RelationPeriod
    - Remove field start_date from relation
    - Remove field end_date from relation
(byvshie) iMac-Alexander:byvshie lorddaedra$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/__init__.py", line 427, in execute_from_command_line
    utility.execute()
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/base.py", line 337, in execute
    output = self.handle(*args, **options)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 62, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/executor.py", line 14, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/loader.py", line 145, in build_graph
    self.load_disk()
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/loader.py", line 103, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/local/Cellar/python3/3.4.0/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/lorddaedra/Projects/byvshie/byvshiebase/migrations/0006_auto_20140418_0411.py", line 8, in <module>
    class Migration(migrations.Migration):
  File "/Users/lorddaedra/Projects/byvshie/byvshiebase/migrations/0006_auto_20140418_0411.py", line 29, in Migration
    bases=(django.db.models.base.NewBase,),
AttributeError: 'module' object has no attribute 'NewBase'
```

**Comment by ghost** [comment]
Little note:

all is ok if I repeat command twice :

``` python
(byvshie) iMac-Alexander:byvshie lorddaedra$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/__init__.py", line 427, in execute_from_command_line
    utility.execute()
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/base.py", line 337, in execute
    output = self.handle(*args, **options)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 103, in handle
    plan = executor.migration_plan(targets)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/executor.py", line 36, in migration_plan
    backwards_plan = self.loader.graph.backwards_plan(target)[:-1]
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 64, in backwards_plan
    return self.dfs(node, lambda x: self.dependents.get(x, set()))
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 119, in dfs
    return _dfs(start, get_children, [])
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 111, in _dfs
    results = _dfs(n, get_children, path) + results
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 111, in _dfs
    results = _dfs(n, get_children, path) + results
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 111, in _dfs
    results = _dfs(n, get_children, path) + results
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 111, in _dfs
    results = _dfs(n, get_children, path) + results
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 111, in _dfs
    results = _dfs(n, get_children, path) + results
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 111, in _dfs
    results = _dfs(n, get_children, path) + results
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/migrations/graph.py", line 103, in _dfs
    raise CircularDependencyError(path[path.index(start):] + [start])
django.db.migrations.graph.CircularDependencyError: [('byvshiebase', '0005_auto_20140414_2154'), ('byvshiebase', '0005_auto_20140414_2154')]
(byvshie) iMac-Alexander:byvshie lorddaedra$ ./manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: default, account, raven_compat, admin, sessions, contenttypes, sites, auth, compressor
  Apply all migrations: auth, byvshiebase
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying byvshiebase.0006_auto_20140418_0411... OK
```

**Comment by ghost** [comment]
Same problem with runserver command... 
Not sure, is it related with Django b1 or pg-fields...

**Comment by lukesneeringer** [comment]
Django 1.7 introduces entirely new migrations that I don't yet have support written for. :)

**Comment by ghost** [comment]
@lukesneeringer 
django-pgfields v1.5a1 works well with 1.7b1 but I tested with latest 1.7.x and it's not compatible:

```
pip uninstall Django
pip install git+https://github.com/django/django@stable/1.7.x

(byvshie) 95-26-89-31:byvshie lorddaedra$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/__init__.py", line 427, in execute_from_command_line
    utility.execute()
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/core/management/__init__.py", line 391, in execute
    django.setup()
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/apps/registry.py", line 106, in populate
    app_config.import_models(all_models)
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/apps/config.py", line 190, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python3/3.4.0/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/lorddaedra/Projects/byvshie/byvshiebase/models.py", line 7, in <module>
    from django_pg.models.fields.uuid import UUIDField
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django_pg/models/__init__.py", line 9, in <module>
    from django_pg.models.base import Model, Manager
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django_pg/models/base.py", line 168, in <module>
    class Model(six.with_metaclass(ModelBase, models.Model)):
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/six.py", line 631, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Users/lorddaedra/Envs/byvshie/lib/python3.4/site-packages/django/db/models/base.py", line 72, in __new__
    module = attrs.pop('__module__')
KeyError: '__module__'
```

maybe you will be interested to know about this bug...

**Comment by lukesneeringer** [comment]
That's interesting. For the moment I'll probably wait to see what happens in Django, since I can't tell if this is a django-pgfields problem or not.

**Comment by ghost** [comment]
It was between Django 1.7 b3 and b4 because of b1, b2 and b3 works ok. But b4 and current master are not.

So this bug is related with at least one of this commits:
https://github.com/django/django/compare/edca57817fa5c366483194020967cd9d4ef1318c...95cf17244c086cb31eef86bdb0db57a0b5d05e38

**Comment by ghost** [comment]
I did not tested it yet, but I think, this bug is related with this commit https://github.com/django/django/commit/f02f20a7395fe6681cfcae1c52d4bab68f6aa0d5

**Comment by lukesneeringer** [comment]
OK, I looked into this, and basically the situation is that Django requires a newer version of six (which matches the change in their vendored version).

I'm bumping the minimum six from 1.4.1 to 1.7.2 in `requirements.txt`, which also seems to address this issue.

**Comment by lukesneeringer** [comment]
With six 1.6.1:

```
(pgfields) luke@bahamut:~/Code/OSS/django-pgfields:master$ python tests/runtests.py
Traceback (most recent call last):
  File "tests/runtests.py", line 24, in <module>
    django.setup()
  File "/Users/luke/.virtualenvs/pgfields/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/luke/.virtualenvs/pgfields/lib/python3.4/site-packages/django/apps/registry.py", line 106, in populate
    app_config.import_models(all_models)
  File "/Users/luke/.virtualenvs/pgfields/lib/python3.4/site-packages/django/apps/config.py", line 190, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/luke/.virtualenvs/pgfields/lib/python3.4/importlib/__init__.py", line 104, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/luke/Code/OSS/django-pgfields/django_pg/models/__init__.py", line 9, in <module>
    from django_pg.models.base import Model, Manager
  File "/Users/luke/Code/OSS/django-pgfields/django_pg/models/base.py", line 168, in <module>
    class Model(six.with_metaclass(ModelBase, models.Model)):
  File "/Users/luke/.virtualenvs/pgfields/lib/python3.4/site-packages/six.py", line 631, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Users/luke/.virtualenvs/pgfields/lib/python3.4/site-packages/django/db/models/base.py", line 72, in __new__
    module = attrs.pop('__module__')
KeyError: '__module__'
```

With six 1.7.2, and no other changes:

```
(pgfields) luke@bahamut:~/Code/OSS/django-pgfields:master$ python tests/runtests.py
Creating test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
    HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES.django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults.If your project needs these middleware then you should configure this setting.
System check identified some issues:

WARNINGS:
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
    HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES.django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults.If your project needs these middleware then you should configure this setting.
System check identified some issues:

WARNINGS:
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
    HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES.django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults.If your project needs these middleware then you should configure this setting.
.............................................ss................................ss..s..ssssssss.........................
----------------------------------------------------------------------
Ran 119 tests in 0.645s

OK (skipped=13)
Destroying test database for alias 'default'...
```
